### ISSUE TITLE
ShdrAdapter: Listen on configurable IP address

### ISSUE THREAD

**Issue by MRIIOT** [TrakHound/MTConnect.NET#20]
IP address to listen on should be configurable with the option to listen on all interfaces (0.0.0.0).

https://github.com/TrakHound/MTConnect.NET/blob/afb85cfdb1dd545ae04d9093039bdc4430b22bb7/src/MTConnect.NET/Adapters/Shdr/AgentClientConnectionListener.cs#L105-L113

**Comment by PatrickRitchie** [comment]
You're correct this should be configurable. I will make an Address property that will default to all interfaces as you mentioned. 

I have a large commit coming up that I will most likely add early next week along with a new Release. I will include this change in with that commit.

**Comment by MRIIOT** [comment]
Looking forward to it.  I'm ready to do more testing.

**Comment by PatrickRitchie** [comment]
This should be fixed in 0e50b3ba0c3403b4c86f5813944cf991ec523c38

The TcpListener now listens on Any address. This may need to be configurable in the configuration file in the future.
```c#
 private async Task ClientListener(CancellationToken cancel)
        {
            do
            {
                try
                {
                    _listener = new TcpListener(IPAddress.Any, Port);
                    _listener.Start();
```

**Comment by MRIIOT** [comment]
Will test in a Docker setup this week.

**Comment by MRIIOT** [comment]
@PatrickRitchie , can you update Nuget package?

**Comment by PatrickRitchie** [comment]
@MRIIOT Yes I will update the Nuget package and create a new Release tonight. I had a few minor other changes that I wanted to include in that Release as well.
