### ISSUE TITLE
SHDR: SetUnavailable

### ISSUE THREAD

**Issue by MRIIOT** [TrakHound/MTConnect.NET#21]
Expected behavior: Calling `adapter.SetUnavailable` should send new SHDR to Agent with value of `UNAVAILABLE`.
Current behavior: It does not.

DataItem before setting `UNAVAILABLE`.

![image](https://user-images.githubusercontent.com/48079336/160887903-bebf3695-fb1e-4cb7-bda3-70e599ac6f30.png)

DataItem after setting `UNAVAILABLE`.

![image](https://user-images.githubusercontent.com/48079336/160888272-16b9afeb-1001-4798-85da-2ef745148cd6.png)

Comparison in `UpdateDataItem`.

![image](https://user-images.githubusercontent.com/48079336/160889485-057c4737-d07a-4ca0-9098-e89d4ec7bd01.png)

![image](https://user-images.githubusercontent.com/48079336/160889629-44fab57b-afd8-49ff-a7b4-35248dc4cb79.png)

**Comment by PatrickRitchie** [comment]
Commit 26fc9363c8639886d5659f7b6171d76f3cdca51d should have fixed this issue.

```c#
var axesDataItem = new ShdrDataItem("f_sim_p1_axes", "X Y Z S");
adapter.AddDataItem(axesDataItem);
```
> 2022-03-30T21:02:26.7850000Z|f_sim_p1_axes|X Y Z S

```c#
adapter.SetUnavailable();
```

> 2022-03-30T21:03:17.8750000Z|f_sim_p1_axes|UNAVAILABLE


This was an issue where I was updating the instance of the ObservationInput object that was in the cached List when setting to Unavailable. This was updating the same object in the List so the "existing.ChangeId != dataItem.ChangeId" comparison was always going to be equal.

I added a few new methods for handling this that instantiate new ObservationInput objects and add them to the cached List. This will prevent the behavior described above. I also added an optional Timestamp parameter to those methods along with any other Unavailable related method.

I tested this with DataItem, Message, Condition, TimeSeries, DataSet, and Table Observations and they all seemed to work correctly.

**Comment by PatrickRitchie** [comment]
Has anyone still had issues with this in the latest versions? If not, I will close this issue.

**Comment by MRIIOT** [comment]
I think I was waiting for a Nuget release to test this.  But close it.

**Comment by PatrickRitchie** [comment]
Ok thanks for letting me know. This update should be in any of the newest Nuget packages. 

A link to the latest package is below:
[MTConnect.NET - Nuget](https://www.nuget.org/packages/MTConnect.NET/)
