### ISSUE TITLE
Addition of MTConnect Adapter Functionality

### ISSUE THREAD

**Issue by PatrickRitchie** [TrakHound/MTConnect.NET#4]
We are looking to add classes to support the MTConnect Adapter communication between the Adapter and Agent using the SHDR protocol to this library and are looking for any feedback or contributions from the community. 

We would like to improve on the open source libraries already out there for Adapters as well as integrate it into this library so it is easily accessible through Nuget.

If anyone has any suggestions or would like to contribute then please feel free to add a comment here or contact us directly at info@trakhound.com

**Comment by intolerance** [comment]
What work still needs to be done?

**Comment by PatrickRitchie** [comment]
This is completed with v3.0.0
